PATH_YACC=C:\Users\marco\Documents\NetBeansProjects\CompilerJPy\src\compilerjpy

all:	
	$(PATH_YACC)\yacc -Jnorun -Jnoconstruct -Jthrows=IOException -Jthrows=Exception -Jpackage=compilerjpy -Jextends=Lexer -Jsemantic=Object parser.y
